#############################################################################
# Makefile for building: RinTinTinvol2
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sun Jun 9 23:17:07 2013
# Project:  RinTinTinvol2.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile RinTinTinvol2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4 -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		Communication/server.cpp \
		Communication/tcpsocket.cpp \
		Communication/socketpool.cpp \
		Communication/communication.cpp \
		Deserialization/pakiet.cpp \
		Parser/protocolparser.cpp \
		Exceptions/badpackageexception.cpp \
		Exceptions/exception.cpp 
OBJECTS       = main.o \
		server.o \
		tcpsocket.o \
		socketpool.o \
		communication.o \
		pakiet.o \
		protocolparser.o \
		badpackageexception.o \
		exception.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RinTinTinvol2.pro
QMAKE_TARGET  = RinTinTinvol2
DESTDIR       = 
TARGET        = RinTinTinvol2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RinTinTinvol2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile RinTinTinvol2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile RinTinTinvol2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RinTinTinvol21.0.0 || $(MKDIR) .tmp/RinTinTinvol21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RinTinTinvol21.0.0/ && $(COPY_FILE) --parents Communication/server.h Communication/tcpsocket.h Communication/socketpool.h Communication/communication.h Deserialization/pakiet.h Parser/protocolparser.h Parser/packettype.h Exceptions/badpackageexception.h Exceptions/exception.h .tmp/RinTinTinvol21.0.0/ && $(COPY_FILE) --parents main.cpp Communication/server.cpp Communication/tcpsocket.cpp Communication/socketpool.cpp Communication/communication.cpp Deserialization/pakiet.cpp Parser/protocolparser.cpp Exceptions/badpackageexception.cpp Exceptions/exception.cpp .tmp/RinTinTinvol21.0.0/ && (cd `dirname .tmp/RinTinTinvol21.0.0` && $(TAR) RinTinTinvol21.0.0.tar RinTinTinvol21.0.0 && $(COMPRESS) RinTinTinvol21.0.0.tar) && $(MOVE) `dirname .tmp/RinTinTinvol21.0.0`/RinTinTinvol21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RinTinTinvol21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp Communication/server.h \
		Communication/tcpsocket.h \
		Communication/socketpool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

server.o: Communication/server.cpp Communication/server.h \
		Communication/tcpsocket.h \
		Communication/socketpool.h \
		Communication/communication.h \
		Parser/protocolparser.h \
		Parser/packettype.h \
		Deserialization/pakiet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o server.o Communication/server.cpp

tcpsocket.o: Communication/tcpsocket.cpp Communication/tcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpsocket.o Communication/tcpsocket.cpp

socketpool.o: Communication/socketpool.cpp Communication/socketpool.h \
		Communication/tcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o socketpool.o Communication/socketpool.cpp

communication.o: Communication/communication.cpp Communication/communication.h \
		Communication/tcpsocket.h \
		Communication/socketpool.h \
		Parser/protocolparser.h \
		Parser/packettype.h \
		Deserialization/pakiet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o communication.o Communication/communication.cpp

pakiet.o: Deserialization/pakiet.cpp Deserialization/pakiet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pakiet.o Deserialization/pakiet.cpp

protocolparser.o: Parser/protocolparser.cpp Parser/protocolparser.h \
		Parser/packettype.h \
		Deserialization/pakiet.h \
		Exceptions/badpackageexception.h \
		Exceptions/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o protocolparser.o Parser/protocolparser.cpp

badpackageexception.o: Exceptions/badpackageexception.cpp Exceptions/badpackageexception.h \
		Exceptions/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o badpackageexception.o Exceptions/badpackageexception.cpp

exception.o: Exceptions/exception.cpp Exceptions/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exception.o Exceptions/exception.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

