#pragma once

enum PacketType {
	PING = 0,
	PONG = 1,
	ADD_USER = 2,
	RESPONSE_ADD_USER = 3,
	CHECK_RESTAURANT = 4,
	RESPONSE_RESTAURANT = 5,
	GET_RESTAURANT = 6,
	RESPONSE_GET_RESTAURANT = 7,
	SEND_NEXT = 8,
	END_OF_DATA = 9,
	GET_COMMENTS = 10,
	RESPONSE_GET_COMMENTS = 11,
	ADD_COMMENT = 12,
	RESPONSE_ADD_COMMENT = 13,
	ADD_RESTAURANT = 14,
	RESPONSE_ADD_RESTAURANT = 15,
	DELETE_COMMENT = 16,
	RESPONSE_DELETE_COMMENT = 17

};